package com.amberved;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppServer {
    public String getGreeting() {
        return "Hello world. Server";
    }

    public static void main(String[] args) {
        System.out.println(new AppServer().getGreeting());
    }
}
