package com.amberved;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppClient {
    public String getGreeting() {
        return "Hello world. Client";
    }

    public static void main(String[] args) {
        System.out.println(new AppClient().getGreeting());
    }
}
